In [7]:
import pandas as pd

In [8]:
import numpy as np

In [10]:
array  = np.array([[94, 89, 63],

                  [93, 92, 48],

                 [92, 94, 56]])
array[ : 2, 1 : ]

array([[89, 63],
       [92, 48]])

In [12]:
my_tuppy = (1,2,5,8)

In [13]:
my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [14]:
y = [(2, 4), (7, 8), (1, 5, 9)]

In [18]:
x = y[1][-1]

In [19]:
S = [['him', 'sell'], [90, 28, 43]]

In [20]:
S[0][1][1]

'e'

In [26]:
df = pd.read_csv('/content/drive/MyDrive/Data/FoodBalanceSheets_E_Africa_NOFLAG.csv',encoding='latin-1')

In [29]:
df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [51]:
grouped_data = df.groupby('Element')['Y2017'].sum()

In [50]:
grouped_data

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [53]:
grouped_data = df.groupby('Element').agg({'Y2017':'sum','Y2016':'sum','Y2015':'sum','Y2015':'sum'})

In [54]:
grouped_data

                                             Y2017       Y2016       Y2015
Element
Domestic supply quantity                2088198.10  2044842.70  2021493.55
Export Quantity                          182338.80   151920.46   157614.47
Fat supply quantity (g/capita/day)        10253.84    10102.77    10235.74
Feed                                     223705.68   228958.65   225050.22
Food                                    1258888.28  1247022.17  1232361.10
Food supply (kcal/capita/day)            454681.00   451810.00   453383.00
Food supply quantity (kg/capita/yr)       48690.04    48985.28    49345.13
Import Quantity                          294559.09   286582.78   267018.46
Losses                                   160614.00   157787.00   155439.00
Other uses (non-food)                     91645.97    69563.68    66254.41
Processing                               292836.00   280631.00   287929.00
Production                              2030056.89  1943537.15  1947019.39
Protein supply quantity (g/capita/day)    11842.45    11779.69    11833.95
Residuals                                 35500.00    37224.00    30045.00
Seed                                      24870.14    23389.20    23976.82
Stock Variation                           54316.91    33140.12    34910.99
Total Population - Both sexes           1112641.00  1085107.00  1058081.00
Tourist consumption                          91.00       89.00      349.00

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [58]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [60]:
df.isna().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [67]:
area_group = df.groupby('Area')['Y2017'].sum().sort_values()

In [68]:
area_group

Area
Sudan (former)                       0.00
Ethiopia PDR                         0.00
Comoros                             59.84
Seychelles                         442.34
Sao Tome and Principe            12662.63
Cabo Verde                       14650.74
Guinea-Bissau                    19102.77
Lesotho                          21267.96
Botswana                         22101.30
Djibouti                         22729.91
Gambia                           23154.18
Gabon                            27979.64
Liberia                          29342.20
Namibia                          29874.89
Central African Republic         29937.00
Congo                            41181.68
Togo                             49841.88
Mauritius                        51114.83
Eswatini                         54343.33
Sierra Leone                     55311.33
Chad                             71594.68
Rwanda                           73663.69
Zimbabwe                         75919.34
Senegal                          95681.15
Guinea                           98138.87
Burkina Faso                    101855.07
Zambia                          103223.77
Tunisia                         124167.20
Benin                           124771.22
Niger                           126707.58
Madagascar                      131197.73
Mali                            149928.33
Mauritania                      156665.46
Mozambique                      161407.98
Malawi                          181098.71
Uganda                          213950.38
Côte d'Ivoire                   224599.01
Angola                          229159.57
Cameroon                        232030.43
Sudan                           239931.92
Kenya                           264660.66
United Republic of Tanzania     322616.85
Algeria                         325644.27
Ghana                           337599.06
Morocco                         388495.36
Ethiopia                        448683.76
South Africa                    517590.54
Egypt                           866379.92
Nigeria                        1483268.23
Name: Y2017, dtype: float64

In [70]:
wine = df[df['Item'] == 'Wine']

In [76]:
wine

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
916,4,Algeria,2655,Wine,5511,Production,1000 tonnes,52.00,10.0,7.0,62.00,54.00
917,4,Algeria,2655,Wine,5611,Import Quantity,1000 tonnes,7.00,8.0,11.0,9.00,9.00
918,4,Algeria,2655,Wine,5072,Stock Variation,1000 tonnes,0.00,0.0,0.0,0.00,0.00
919,4,Algeria,2655,Wine,5911,Export Quantity,1000 tonnes,0.00,0.0,0.0,0.00,0.00
920,4,Algeria,2655,Wine,5301,Domestic supply quantity,1000 tonnes,59.00,18.0,18.0,71.00,63.00
...,...,...,...,...,...,...,...,...,...,...,...,...
60551,181,Zimbabwe,2655,Wine,5142,Food,1000 tonnes,4.00,4.0,4.0,4.00,4.00
60552,181,Zimbabwe,2655,Wine,645,Food supply quantity (kg/capita/yr),kg,0.31,0.3,0.3,0.26,0.31
60553,181,Zimbabwe,2655,Wine,664,Food supply (kcal/capita/day),kcal/capita/day,1.00,1.0,1.0,0.00,1.00
60554,181,Zimbabwe,2655,Wine,674,Protein supply quantity (g/capita/day),g/capita/day,0.00,0.0,0.0,0.00,0.00
60555,181,Zimbabwe,2655,Wine,684,Fat supply quantity (g/capita/day),g/capita/day,0.00,0.0,0.0,0.00,0.00

In [80]:
grouped_data = wine.groupby('Item').agg({'Y2018':'sum','Y2015':'sum'})

In [81]:
grouped_data

        Y2018    Y2015
Item
Wine  4039.32  4251.81

In [84]:
pro_mad = df[(df['Element'] == 'Protein supply quantity (g/capita/day)') & (df['Area'] == 'Madagascar')]

In [85]:
total = pro_mad.groupby(['Area', 'Element'], as_index = False)['Y2015'].sum()

In [86]:
total

         Area                                 Element   Y2015
0  Madagascar  Protein supply quantity (g/capita/day)  173.05

# New Section